version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail
    environment:
      ADOBE_AIR_HOME: /usr/local/share/adobe-air-sdk
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Fix 'Homebrew must be run under Ruby 2.3!'
          command: brew update
      - run:
          name: Homebrew Depenendcies
          command: ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew/
            - vendor/bundle
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "ab:48:b1:f2:a7:e9:0f:ba:81:3b:0c:16:48:6b:91:3d"
      - run:
          name: Build Teak Cleanroom
          command: bundle exec rake package:download build:air $RAKE_BUILD_TASKS
      - persist_to_workspace:
          root: .
          paths:
            - teak-air-cleanroom.ipa
            - teak-air-cleanroom.apk
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run: git fetch --tags
      - restore_cache:
          key: v0-{{ checksum "Gemfile.lock" }}
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - run:
          name: Install AWS CLI
          command: sudo apt-get -y -qq install awscli
      - save_cache:
          paths:
            - vendor/bundle
          key: v0-{{ checksum "Gemfile.lock" }}
      - attach_workspace:
          at: .
      - run:
          name: Upload Cleanroom Apps to S3
          command: bundle exec rake $RAKE_DEPLOY_TASKS
workflows:
  version: 2
  android:
    jobs:
      - build:
          context: android-cleanroom
      - deploy:
          context: android-cleanroom
          requires:
            - build
          filters:
            branches:
              only: [master, /hotfix.*/]
  ios:
    jobs:
      - build:
          context: ios-cleanroom
      - deploy:
          context: ios-cleanroom
          requires:
            - build
          filters:
            branches:
              only: [master, /hotfix.*/]
