version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    shell: /bin/bash --login -eo pipefail
    environment:
      ADOBE_AIR_HOME: /usr/local/share/adobe-air-sdk
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Homebrew Depenendcies
          command: ./setup
      - run:
          name: Ruby Gems
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - ~/Library/Caches/Homebrew/
            - vendor/bundle
          key: v0-{{ checksum "setup" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Build Teak Cleanroom
          command: ./compile
      - persist_to_workspace:
          root: .
          paths:
            - teak-air-cleanroom.ipa
            - teak-air-cleanroom.apk
  deploy:
    docker:
      - image: circleci/ruby:latest
    steps:
      - attach_workspace:
          at: .
      - run: git fetch --tags
      - run:
          name: Upload Cleanroom Apps to S3
          command: rake deploy:ios deploy:android
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: [master, /hotfix.*/]
